name: code-snippets

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore CodeSnippets/CodeSnippets.sln
    - name: Build
      run: dotnet build CodeSnippets/CodeSnippets.sln --no-restore
    - name: Test
      run: dotnet test CodeSnippets/CodeSnippets.sln --no-build --verbosity normal
